### ISSUE TITLE
Investigate alternatives to Sourcebuster (the JS library we're currently using)

### ISSUE THREAD

**Issue by rawdreeg** [woocommerce/woocommerce-order-source-attribution#1]
## Description

The extension currently relies on [Sourcebuster JS](https://github.com/alex35mil/sourcebuster-js) to track the sources of sites' visitors and store the data in the cookies for further analysis. 

Given the implications of using cookies in this process, it seems that we’ll want to avoid them.

More info: pe2C5g-ur-p2

## Tasks.

- [x] Look into [Trafficsourcetracker.js](https://marketlytics.github.io/trafficSourceTracker.js/)
- [x] Look into [trak.js](https://github.com/mrmartineau/trak.js)
- [x] Look into [visitdatajs](https://github.com/ilkkapeltola/visitdata)
- [x] Document findings
