### ISSUE TITLE
Design i1.5 updates

### ISSUE THREAD

**Issue by JPry** [woocommerce/woocommerce-order-source-attribution#57]
Internal discussion: pe2C5g-HR-p2
Figma: zbcskVHHx3bqMjuFCEFEIN-fi-227-8716

### Discussion Summary

As part of next steps before launching the Order Attribution feature in Woo, we are looking to make a few UI changes.

There is agreement to go the direction of adding a Customer History widget that will contain `Total orders`, `Total spend`, and `Average order value`. This info can be pulled from the Customers page.

The term `Total orders` is a slight change from the original term `Orders`. We think `Total Orders` does a better job conveying our meaning. A tooltip has been added for good measure, which will contain the text:

> Total of completed orders by this customer, including the current one. Excludes cancelled or refunded.

If we make this change, the term should be the same in both places (orders widget and Customers page).

For the settings page, the following text will be used:

> Enable this feature to track and credit channels and campaigns that contribute to orders on your site.

### Proposed changes

```[tasklist]
### Tasks
- [x] ~Remove the link to Go to channel for now~ I don't believe we currently have the Go to Channel link
- [ ] https://github.com/woocommerce/woocommerce-order-source-attribution/issues/61
- [ ] https://github.com/woocommerce/woocommerce-order-source-attribution/issues/62
- [ ] https://github.com/woocommerce/woocommerce-order-source-attribution/issues/58
- [ ] https://github.com/woocommerce/woocommerce-order-source-attribution/issues/65
- [ ] https://github.com/woocommerce/woocommerce-order-source-attribution/issues/67
```

**Comment by JPry** [comment]
I've created the [`feature/design-i1.5`](https://github.com/woocommerce/woocommerce-order-source-attribution/compare/develop...feature/design-i1.5) branch to pull all of these changes together as they are worked on.

The PR is #60
