### ISSUE TITLE
Start planning for what hooks will be put in place to control tracking data and features

### ISSUE THREAD

**Issue by JPry** [woocommerce/woocommerce-order-source-attribution#6]
Identify hooks needed to control tracking data.

- [x] Add hook to filter tracking cookie params (session length, cookie lifetime)
- [x] Add hook to filter tracking data.
- [x] Add filter hook to disable tracking.
- [x] Document hooks
